c = "IHRHGFTVEEEENNPOAIAOLARAEIEETINNBKLSPREEETNRMRAHSENEUNIIUMNDDTANWREAMOAYDMCDJNERETSNADAANFBYOAYMIDOILJKRBGWHIUANFTGBRESVMTFTAOAEEOOSERYOEEASANDTETVODIOERSMSNNLCSHEENNURYALIAWNWPUDSUANNNEECMRCENANROITPLETBRRUYGHSTNENLOLGIOUEEGIASTFOLEEYRSMKIITTITDHCFSINSOUCEIISEANOTEREMESINGIIANEACVWENMEIDRAEOTRDSRONRCOTTTTATGCUOLBEMESTDRFAIRIEAANMTDUROIELDDLEENFCUPAEWHTTLHNGCNRSNATDRANTELIICNFDEEOREIVVEESONIEHFSNHNATLREAWUOOSTATRISOSAOTSDSSASRISIIEARONDESTRUOWEAESNLHTMENEIGKDDSTBELDUIPTNWAELMSDERTIOYEMGHWLODPUULVSTTDEMLGPCEODHPITREAHFRHSYABTUNDOECOEEPRSSTDWIENMNMOIDFRMEINHYECSSUDNMUNDSOSTAUCMDENRADVTTAROTSNLAISNISKUENCAEPELGATSDEEAIRDSHBITOEGPBODEEFDISRODNISTTSUEUCTSACGWDROENOONIRWDENNTODICINOMNLLOSSEOTFREOLMACSOOPSDOHDFIRGKTNECIROEROOHWBCCPNOARDITNBKCAENOBIEUDTYEYOOFIGAMUDHGRCBONEORHHIREHEEROINSDRNUTETIAAIXUASOIEIEIDTRTENNZMCTOLECSCIDNENCNPVOTTDOEGEOOOHDDRNFWUHENNAIURTSEDDDSSIYSRHHELNEOSOUSNELVTMDGNWDTDAAMELXANEFEIENRECTOUNSKKODTASHNGGEEIOTEELEUENRISOROANGALNTFCDRVUINMDDAUHNLNMIVADFNEBGOARRITEEOAERENNREIREDERDIEDRULDBITISYATENEOLFDSHERNRETBEIILOTOBDTOWRIRNSDANHEEAUEETNSTNMREMTSMEOTLESTUHEIIIAIATPGMEHTEAABMENTCNEATEBNIDERGNTIDCRFNWCRHRNRDPREOORRATOOUSARCNBGTHHMLTETPIAEEICFEFNLDTOPNNAINIHTAATTNTIDIOEETNREEMRHEHABHGTTSENUOEIESTDEIOSINHCTSTBNNDRCANENHNAWTNIYTHAITASPSSCOEAOHATHBDOTBRDTMECINWEGEGHEREERNBOLHEKANSNDFASRXIYEOAGLTNESEMIAIIYNGAXURETLATEUGENTPHNCCLSEHTIDRLIAEPIBEAIYOOCVNIWRTLYEOAFITBHWOOLTATMPOFSGFLWIODNFVTATEDADREUETHCOEWAMWNENGNREWPIAATDEPOSIETEWMAHESRRAEHIASTFHATNNERDTCSEUMNSDNETOTTNEWRITMLDEHGDMEHEABHSWSSOASRTDTHDYDEGEOHOEFNIGIAHEIYMEATUOESTERXUACEDVHTTAHNNOFSRTLNBUIERTIAEEDMWTPCRREDEELHETHIEEEUUEISLIRITMCHYEHLVBTOTVAAFOBDAOPMWLNODTLTSNHWOATIBEEDXOTTTEIRTHSPMOONGNEPHBOSOUOLFNHAGDTESIGLTNETTEATTRDMOLYVSMESEAGENSNEEOFNTOWTFPRSRWNRIRFAEGHEFLISOUIOTRAYTNHIHSPEESFLIEDIGRSEEAIYARESAHNNPIGESTTAXOSEIIYGAENGPETDNGEFEHOTEARPCWENNONTBRDERVLOEOTNOIGMRNEEOHRESSOSDUDRLOFATLEEECIHNTETBDHUCRHBAOEASITWTNSSNMHOOLLAONIGOHCETSOSECDRIONIHXAEMSAROSRUNRCAOHHOIVAIAATNISVTHSNOHOSWUETYISEREYOHNTEERLRNIMSLEHGTNTEEOROSTOCENENAFELEBHDTOWHEIDOSERTTSAOXTUIERSTFSTINPWIDIEEELWCWAIFHCCOAHLOHCVPNERXOHHACEEIEEECEAOANWTMMTCODNHDEEDBFENASCEAOSBTMKLNSGOHCNBPUDRKYOEYSEDETTSRENFHHEHETSOSUWUADEESTAOOEYTBAHLXWSYNIMLEFATETIAOSRPAIEATNNISROHSHMNBNAGROEBTOSENEHHESELDOMBOSSFTUEDUEHAESTUOAXGTSDITSETPTDBWDFRTAIYRTREETIERESNDHOALSTOCIETRNHTEDCPMEOESTHOOAEEARDAERUYNSNHHESREEFOOLAOTTNTTSIOWRILOSETNEIAERTPNFHYOPEBRNRANOIRNAMODHUTMTESNSTHUBKPOMNEICITSCREVAEFIKQBHCEICCENHTASTERSUAOSOOIAGFFNSTPOEEEIIEPENOSRMHTTOEMRAADATUNISEOUSMMALNKBSBTEFCEUFNRDUNYASOTESCERGOBOTYGNDHUNHEAITEUEEARTNIOUYPEORWUNTNEIEAOCGRTCRRAMNNTSCIUQSHTIIAGTNHREEIESKAUDAAXTSHUTEHAHERESOEIECOVTBOSGDIJTNNNTOUMSEALUIAFAODFNAEINDAFTYTATENKGWRNOAETRYESOSTNDATWNRSNRUNESEOEISNEEOITMRMNWTTOIAOTTRNNWATNWTYWSYTIINORDAAOOHAEHESINWJGTRHSNVNRTTEEONGOCEHKEEFRRISKHESEOGKHIRSIFPAGDNIFOADOEAREWKGHTITOWREEAERCORUWFUTOHEUECFTNCRENOTOEOITGACETRAOYOICEIUTNEESITDIODHEOENLSHOEISUSBDTNARUOTENERSDEARSTDTADEEPEWTIUDANITPRIPHNIOENOETEPTRVGAGRMRNUHUIRRVSEISGCLICMAUSSTIOOMANTEAEOYSDFRREEDNTDSREOANSAYFGFRIMCTOLOAFMYITEMRIUTLSPTBEGFNNPNTSAUAOKGTYAVEIOMNYTRNOEMHIGSSKANPHFCRNRTATOOEATPEDOUHTNOEWTBELDSEDIDDEBOCBEEPTIOVEAEATSRSEEEIDLPIWRSPUHBADVEHTNNFLROENTOAIHUSEHNWEFFGDLTTOSEETEUDDHEVREEUNFUETAAWHAEOVTMCARRHITSWLHONHEU"
number = len(c)
ciphertext = [[['' for i in range(5)] for k in range(26)] for z in range(25)]
temp1 = [[['' for i in range(5)] for k in range(26)] for z in range(25)]
temp2 = [[['' for i in range(5)] for k in range(26)] for z in range(25)]
keyword1 = [3, 1, 2, 0, 4]
keyword2 = [11, 7, 10, 3, 17]
l = 0
f = 0
x = 0
##print(temp1)
##for h in range(0, number, 125): #130 if extended
##    for j in range(125):
##        if j % 5 != 4:
##            print(c[h+j], end = '\t')
##        elif j % 5 == 4:
##            print(c[h+j], end = '\n')
##    print('\n')
for z in range(25):
    for k in range(26):
        for i in range(5):
            if (l+f+x)<3250:
                ciphertext[z][k][i] = c[l+f+x]
                x +=1
        f +=1
    l +=1
print(ciphertext)
for z in range(25):
    for k in range(26):
##        for m in range(keyword2[0]+1):
            for i in range(5):
                temp1[z][k][keyword1[i]] = ciphertext[z][k][i]
##                temp2[z][keyword2[i] - m][i] = temp1[z][k-m][i]
print(temp1[0][0][-1])
print(temp1)
print(temp2)
